[package]
name = "kvstore"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
argon2 = "0.5.3"
futures = "0.3.30"
rand = "0.8.5"
regex = "1.10.3"
tokio = { version = "1.36.0", features = ["full"] }
